# 예외 필터

> "Everything fails all the time."
>
> Werner Vogels, AWS CTO

어떤 상황에서든 에러는 난다. 대응책을 마련해두어야 하는 것은 필수다. 그렇다면 예외처리 코드를 어디 두는 것이 좋을까?

에러가 발생할 만한 **모든 곳**에 두는 것은 적절하지 않다. 코드 관리는 어떻게 할 것이며, 핵심기능 구현 이해를 방해한다.

그렇다면 별도의 모듈을 두고 에러를 공통으로 처리할 수 있도록 해보자.

## 12.1 예외 처리

Nest는 프레임워크에 예외 레이어를 두고있다. 기본적인 예외처리는 Nest 단에서 처리된다. 에러를 발생시켜보자.

```ts
import { InternalServerErrorException } from '@nestjs/common';

@Controller()
export class AppController {
  (생략)

  @Get('/error')
  error(foo: any): string {
    return foo.bar();   // foo는 Undefined니, 에러가 터진다.
  }
}
```

이러면 응답값으로 500에러를 리턴하며, JSON 형식으로 처리한다. 이 필터는 인식할 수 없는 에러(`HttpException`도 아니고, `HttpException`을 상속받은 에러를 의미)를 `InternalServerErrorException` 으로 변환해준다.

```shell
❯ http GET localhost:3000/error
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 52
Content-Type: application/json; charset=utf-8
Date: Sat, 05 Aug 2023 18:14:30 GMT
ETag: W/"34-rlKccw1E+/fV8niQk4oFitDfPro"
Keep-Alive: timeout=5
X-Powered-By: Express

{
    "message": "Internal server error",
    "statusCode": 500
}

```

HTTP response의 400 에러 Bad Request에 해당하는 예외처리 코드(`BadRequestException`)를 살펴보자:

```ts
@Get('/:id')
async getUserInfo(@Param('id') userId: string): Promise<UserInfo> {
  if (+userId < 1) {
    throw new BadRequestException('id is greater than 0');
  }
  return await this.usersService.getUserInfo(userId);
}
```

```shell
❯ http GET localhost:3000/users/0
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 73
Content-Type: application/json; charset=utf-8
Date: Sat, 05 Aug 2023 19:02:59 GMT
ETag: W/"49-Q1p8MmyyLVw412Aew2fgB5Cauvw"
Keep-Alive: timeout=5
X-Powered-By: Express

{
    "error": "Bad Request",
    "message": "id is greater than 0",
    "statusCode": 400
}

```

Nest의 기본 예외 클래스를 살펴보자. 보다 상위의 클래스는 `HttpException` 이므로, 이를 상속해서 사용하려면 아래와 같이 사용한다.

```ts
throw new HttpException(
  {
    errorMessage: 'id is greater than 0',
    foo: 'bar'
  },
  HttpStatus.BAD_REQUEST
)
```

`BadRequestException` 의 구현체는 아래와 같다([출처](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/bad-request.exception.ts)):

```ts
export class BadRequestException extends HttpException {
  constructor(
    objectOrError?: string | object | any,
    descriptionOrOptions: string | HttpExceptionOptions = 'Bad Request',
  ) {
    const { description, httpExceptionOptions } =
      HttpException.extractDescriptionAndOptionsFrom(descriptionOrOptions);

    super(
      HttpException.createBody(
        objectOrError,
        description,
        HttpStatus.BAD_REQUEST,
      ),
      HttpStatus.BAD_REQUEST,
      httpExceptionOptions,
    );
  }
}
```

이런 식으로, 필요에 의해 HttpException을 상속받은 클래스를 만든다면 이렇게 접근하면 된다.

그 외의 HTTP status code에 해당하는 Nest의 표준 예외는 [해당 링크](https://docs.nestjs.com/exception-filters) 를 참조하여 살펴보자.


## 12.2 예외 필터

Nest의 전역필터 이외에도 예외 필터 레이어를 두어 원하는 대로 예외처리를 수행할 수도 있다.

예외 발생 시 모든 예외(`Error`, 모든 예외의 상위 객체) 를 잡아서 요청 URL과 예외 발생시각을 콘솔에 찍는 필터를 만들어보자:

- 모듈 생성

> `nest g mo exception` -> `exception` 모듈 생성

- 코드 상세

> `src/exception/http-exception.filter.ts`

```ts
import {
  ArgumentsHost,
  Catch,
  ExceptionFilter,
  HttpException,
  InternalServerErrorException,
} from '@nestjs/common';
import { Request, Response } from 'express';

@Catch()    // 처리되지 않는 예외를 잡는 방안
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: Error, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const res = ctx.getResponse<Response>();
    const req = ctx.getRequest<Request>();

    if (!(exception instanceof HttpException)) {    // HttpException이 아닌 경우, InternalServerErrorException으로 처리
      exception = new InternalServerErrorException();
    }

    const response = (exception as HttpException).getResponse();

    const log = {
      timestamp: new Date(),
      url: req.url,
      response,
    };

    console.log(log);

    res.status((exception as HttpException).getStatus()).json(response);
  }
}
```

이런 예외처리는 `@UseFilter` 데코레이터를 엔드포인트, 컨트롤러, 애플리케이션 단위로 설정할 수 있다.

- 엔드포인트 설정방안

```ts
@Controller('users')
export class UsersController {
  (생략)

  @UseFilters(HttpExceptionFilter)
  @Post()
  async createUser(@Body(ValidationPipe) dto: CreateUserDto): Promise<void> {
    this.printLoggerServiceLog(dto);

    const { name, email, password } = dto;
    await this.usersService.createUser(name, email, password);
  }
  (중략)
```

- 특정 컨트롤러 전체에 적용

```ts
@Controller('Users')
@UseFilters(HttpExceptionFilter)
export class UsersController {
  (중략)

```

- 애플리케이션 전체에 적용

```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
  (생략)
  app.useGlobalPipes(
    // new ValidationPipe({
    //   transform: true,
    // }),
  );
  app.useGlobalFilters(
    new HttpExceptionFilter(); // 전역 필터로 적용
  )
  await app.listen(3000);
}
```

그런데 이런 식으로 사용하면, 필터에 의존성을 주입할 수 없다. 예외 필터의 수행이 예외 발생 모듈 외부(`main.ts`)에서 발생하기 때문이다.

의존성 주입을 위해서는 예외 필터를 커스텀 프로바이더로 등록 후, 타 프로바이더를 주입받아 사용한다.

> `src/exception/exception.module.ts`

```ts
import { Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';
import { HttpExceptionFilter } from './http-exception.filter';

@Module({
  providers: [
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class ExceptionModule {}

```

이후 `HttpExceptionFilter` 에서 프로바이더 주입받은 후 사용:

> `src/exception/http-exception.filter.ts`

```ts
import {
  (생략)
  Logger,
} from '@nestjs/common';
import { Request, Response } from 'express';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  constructor(private logger: Logger) {}

  catch(exception: Error, host: ArgumentsHost) {
    (생략)

    this.logger.log(log);

    res.status((exception as HttpException).getStatus()).json(response);
  }
}

```

try/catch 로 잡지 못한 예외를 캐치하는 것은 나머지 생명주기를 무시하고 예외 필터 로직을 탄다는 것에 유의하자.

## 12.3 유저 서비스에 예외 필터 적용하기

`LoggerService` 와 `HttpExceptionFilter` 를 사용하여 처리해보자.

> `src/exception/exception.module.ts`

```ts
import { Logger, Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';
import { HttpExceptionFilter } from './http-exception.filter';

@Module({
  providers: [
    Logger,
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class ExceptionModule {}

```

이 후 `ExceptionModule` 을 `AppModule`로 가져온다.

> `src/app.module.ts`

```ts
@Module({
  imports: [
    (생략)
    ExceptionModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
```

> 🍅 tips
>
> `nest g mo exception` 으로 생성하면
>
> 자동으로 모듈을 import 한다.

그리고 콘솔로그 대신, Logger를 통해 로그를 찍도록 하고, 콜스택을 함께 보도록 `HttpExceptionFilter`를 수정해보자.

```ts
@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  constructor(private logger: Logger) {}

  catch(exception: Error, host: ArgumentsHost) {
    (생략)
    const stack = exception.stack;
    
    (생략)
    const log = {
      timestamp: new Date(),
      url: req.url,
      response,
      stack,
    };

    this.logger.log(log);
    (후략)
```
